// Code generated by goequal for type: Y; DO NOT EDIT
package testdata

func EqualY(t1, t2 *Y) bool {
	if t1 == t2 {
		return true
	}
	if t1 == nil || t2 == nil {
		return false
	}
	if t1.F1 != t2.F1 {
		return false
	}
	return true
}
