// Code generated by goequal for type: X; DO NOT EDIT
package testdata

import "bytes"

func EqualX(t1, t2 *X) bool {
	if t1 == t2 {
		return true
	}
	if t1 == nil || t2 == nil {
		return false
	}
	if t1.F1 != t2.F1 {
		return false
	}
	if t1.F2 != t2.F2 {
		return false
	}
	if !bytes.Equal(t1.F3, t2.F3) {
		return false
	}
	if len(t1.F4) != len(t2.F4) {
		return false
	}
	for i1 := range t1.F4 {
		if t1.F4[i1] != t2.F4[i1] {
			return false
		}
	}
	if t1.F5 != t2.F5 {
		return false
	}
	if len(t1.F6) != len(t2.F6) {
		return false
	}
	for key1, value11 := range t1.F6 {
		if value12, ok := t2.F6[key1]; !ok {
			return false
		} else {
			if value11 != value12 {
				return false
			}
		}
	}
	if len(t1.F7) != len(t2.F7) {
		return false
	}
	for key1, value11 := range t1.F7 {
		if value12, ok := t2.F7[key1]; !ok {
			return false
		} else {
			if len(value11) != len(value12) {
				return false
			}
			for i1 := range value11 {
				if value11[i1] != value12[i1] {
					return false
				}
			}
		}
	}
	if len(t1.F8) != len(t2.F8) {
		return false
	}
	for i1 := range t1.F8 {
		if len(t1.F8[i1]) != len(t2.F8[i1]) {
			return false
		}
		for key1, value11 := range t1.F8[i1] {
			if value12, ok := t2.F8[i1][key1]; !ok {
				return false
			} else {
				if value11 != value12 {
					return false
				}
			}
		}
	}
	if t1.F9 != t2.F9 {
		if t1.F9 == nil || t2.F9 == nil {
			return false
		}
		if (*t1.F9) != (*t2.F9) {
			return false
		}
	}
	if t1.F10 != t2.F10 {
		if t1.F10 == nil || t2.F10 == nil {
			return false
		}
		if len((*t1.F10)) != len((*t2.F10)) {
			return false
		}
		for i1 := range *t1.F10 {
			if (*t1.F10)[i1] != (*t2.F10)[i1] {
				return false
			}
		}
	}
	if len(t1.F11) != len(t2.F11) {
		return false
	}
	for i1 := range t1.F11 {
		if len(t1.F11[i1]) != len(t2.F11[i1]) {
			return false
		}
		for key1, value11 := range t1.F11[i1] {
			if value12, ok := t2.F11[i1][key1]; !ok {
				return false
			} else {
				if value11 != value12 {
					if value11 == nil || value12 == nil {
						return false
					}
					if len((*value11)) != len((*value12)) {
						return false
					}
					for i2 := range *value11 {
						if (*value11)[i2] != (*value12)[i2] {
							return false
						}
					}
				}
			}
		}
	}
	if !EqualY((&t1.F12), (&t2.F12)) {
		return false
	}
	if len(t1.F13) != len(t2.F13) {
		return false
	}
	for i1 := range t1.F13 {
		if !EqualY(t1.F13[i1], t2.F13[i1]) {
			return false
		}
	}
	if len(t1.F14) != len(t2.F14) {
		return false
	}
	for key1, value11 := range t1.F14 {
		if value12, ok := t2.F14[key1]; !ok {
			return false
		} else {
			if value11 != value12 {
				return false
			}
		}
	}
	if len(t1.F15) != len(t2.F15) {
		return false
	}
	for key1, value11 := range t1.F15 {
		if value12, ok := t2.F15[key1]; !ok {
			return false
		} else {
			if !EqualY(value11, value12) {
				return false
			}
		}
	}
	if len(t1.F16) != len(t2.F16) {
		return false
	}
	for i1 := range t1.F16 {
		if len(t1.F16[i1]) != len(t2.F16[i1]) {
			return false
		}
		for i2 := range t1.F16[i1] {
			if t1.F16[i1][i2] != t2.F16[i1][i2] {
				return false
			}
		}
	}
	if len(t1.F17) != len(t2.F17) {
		return false
	}
	for key1, value11 := range t1.F17 {
		if value12, ok := t2.F17[key1]; !ok {
			return false
		} else {
			if len(value11) != len(value12) {
				return false
			}
			for key2, value21 := range value11 {
				if value22, ok := value12[key2]; !ok {
					return false
				} else {
					if value21 != value22 {
						return false
					}
				}
			}
		}
	}
	return true
}
