// Code generated by goequal for type: B; DO NOT EDIT
package testdata

func EqualB(t1, t2 *B) bool {
	if t1 == t2 {
		return true
	}
	if t1 == nil || t2 == nil {
		return false
	}
	if !EqualA((&t1.a), (&t2.a)) {
		return false
	}
	if t1.b != t2.b {
		return false
	}
	return true
}
