// Code generated by goequal for type: A; DO NOT EDIT
package testdata

func EqualA(t1, t2 *A) bool {
	if t1 == t2 {
		return true
	}
	if t1 == nil || t2 == nil {
		return false
	}
	if len(t1.d) != len(t2.d) {
		return false
	}
	for i1 := range t1.d {
		if len(t1.d[i1]) != len(t2.d[i1]) {
			return false
		}
		for key1, value11 := range t1.d[i1] {
			if value12, ok := t2.d[i1][key1]; !ok {
				return false
			} else {
				if len(value11) != len(value12) {
					return false
				}
				for i2 := range value11 {
					if value11[i2] != value12[i2] {
						return false
					}
				}
			}
		}
	}
	return true
}
